### ISSUE TITLE
Reputation detection is wrong

### ISSUE THREAD

**Issue by Tarram1010** [keykey5/BC-BOT-repository#5]
In the Denial Bar, dominants with reputation <=50 are considered subs.
In the Casino, dominants with reputation <50 are considered subs.

The code was probably written before the Dominant/Submissive stat got changed.

**Comment by Tarram1010** [comment]
fixed it with #6

**Comment by keykey5** [comment]
I don't remember if initially BC dominant reputation went from 0 to 100. Actually I think it was always -100 to 100.

The reason it is set to >50 is just because i wanted to assign the dom role only to players that had a some commitment in the role. Initially it was set to >80 but I noticed it was too strict and there was a lack of doms so a I relaxed the requirement to improve the room mix.
I am okay to lower it more if needed to balance the room but I would not like to go too lover (25 maybe?), it's better if new players familiarize with BC e but before getting the dom role. 

You can give me your opinions here or on discord.

**Comment by Tarram1010** [comment]
fair enough for the rep check.. was thinking about it from a math point of vue.. but it makes sense to have the threshold at 50
